# Generated by Django 6.0.5 on 2026-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verify_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('zh', 'Chinese'), ('en', 'English'), ('id', 'Indonesian')], default='en', help_text='Preferred language for UI and message translations', max_length=2),
        ),
    ]
