# Generated by Django 6.0.5 on 2026-05-23 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_zh', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('description_zh', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('vacation_home', 'Vacation Home'), ('guest_house', 'Guest House'), ('hotel', 'Hotel'), ('other', 'Other')], default='villa', max_length=20)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('beds', models.IntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('max_guests', models.IntegerField(default=2)),
                ('min_nights', models.IntegerField(default=1)),
                ('max_nights', models.IntegerField(default=30)),
                ('highlights', models.JSONField(default=list)),
                ('pool', models.BooleanField(default=False)),
                ('instant_book', models.BooleanField(default=False)),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', max_length=10)),
                ('check_in_from', models.TimeField(blank=True, null=True)),
                ('check_in_until', models.TimeField(blank=True, null=True)),
                ('check_out_by', models.TimeField(blank=True, null=True)),
                ('house_rules', models.JSONField(default=list)),
                ('weekend_premium_pct', models.IntegerField(default=0)),
                ('base_price_idr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_price_cny', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cleaning_fee_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('review_count', models.IntegerField(default=0)),
                ('cover_photo_url', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villas', to='users.hostprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_villas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'villas',
            },
        ),
        migrations.CreateModel(
            name='VillaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('caption_zh', models.CharField(blank=True, max_length=300)),
                ('caption_en', models.CharField(blank=True, max_length=300)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='villas.villa')),
            ],
            options={
                'db_table': 'villa_photos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Booked')], default='available', max_length=20)),
                ('price_override_idr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='villas.villa')),
            ],
            options={
                'db_table': 'availability',
                'unique_together': {('villa', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VillaAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label_zh', models.CharField(blank=True, max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('essentials', 'Essentials'), ('kitchen', 'Kitchen'), ('outdoor', 'Outdoor'), ('entertainment', 'Entertainment'), ('safety', 'Safety'), ('accessibility', 'Accessibility')], default='essentials', max_length=30)),
                ('is_highlight', models.BooleanField(default=False)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='villas.villa')),
            ],
            options={
                'db_table': 'villa_amenities',
                'unique_together': {('villa', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='villas.villa')),
            ],
            options={
                'db_table': 'wishlists',
                'unique_together': {('user', 'villa')},
            },
        ),
    ]
