# Generated by Django 6.0.5 on 2026-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('pending_review', 'Pending Review')], default='draft', max_length=20),
        ),
    ]
