# Generated by Django 6.0.5 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_alter_villa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='villaamenity',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
