# Generated by Django 6.0.5 on 2026-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0003_add_available_to_villaamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
