# Generated by Django 6.0.5 on 2026-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_cleanliness', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_checkin', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_location', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_communication', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('text_original', models.TextField()),
                ('text_original_lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], default='zh', max_length=5)),
                ('text_translated', models.TextField(blank=True)),
                ('text_translated_lang', models.CharField(blank=True, max_length=5)),
                ('host_response', models.TextField(blank=True)),
                ('host_replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-published_at'],
            },
        ),
    ]
