# Generated by Django 6.0.5 on 2026-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_original', models.TextField()),
                ('body_original_lang', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], default='zh', max_length=5)),
                ('body_translated', models.TextField(blank=True)),
                ('body_translated_lang', models.CharField(blank=True, choices=[('zh', 'Chinese'), ('en', 'English')], max_length=5)),
                ('attachment_url', models.URLField(blank=True, max_length=500)),
                ('attachment_type', models.CharField(blank=True, max_length=20)),
                ('is_read_by_guest', models.BooleanField(default=False)),
                ('is_read_by_host', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_preview', models.CharField(blank=True, max_length=300)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('guest_unread_count', models.IntegerField(default=0)),
                ('host_unread_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='bookings.booking')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
