# Generated by Django 6.0.5 on 2026-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_add_read_at_and_confidence_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='translations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='body_original_lang',
            field=models.CharField(choices=[('zh', 'Chinese'), ('en', 'English'), ('id', 'Indonesian')], default='zh', max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='body_translated_lang',
            field=models.CharField(blank=True, choices=[('zh', 'Chinese'), ('en', 'English'), ('id', 'Indonesian')], max_length=5),
        ),
    ]
