# Generated by Django 6.0.5 on 2026-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.IntegerField()),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('nightly_rate_idr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cleaning_fee_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_fee_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_idr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_price_cny', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cleaning_fee_cny', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee_cny', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_cny', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cny', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mid_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('awx_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('client_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('fx_quote_id', models.CharField(blank=True, max_length=200)),
                ('fx_quote_expires_at', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('promo_discount_idr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('additional_guests', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('pending_approval', 'Pending Approval'), ('confirmed', 'Confirmed'), ('in_house', 'In House'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('special_requests', models.JSONField(default=dict)),
                ('host_note', models.TextField(blank=True)),
                ('host_responded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
