# Generated by Django 6.0.5 on 2026-05-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_note',
            field=models.TextField(blank=True),
        ),
    ]
